version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      - MYSQL_DATABASE=auth
      - MYSQL_USER=auth
      - MYSQL_PASSWORD=auth
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
  auth:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    expose:
    - 8080
    environment:
    - JWT_PUBLIC=ghZ4Eb-LT2tcCfWI6Szxu25kLQ3LOADA-KydgxASz_jMb5IHxMQIwMKFXe5qQ8lIG1lFhdu2G51GdXA8vaY148UtYt_COUnQSYOfIhcp7WpPXXhu83vqjET78CzkLsDI8VmF-9d8dHvtSVUqXfkk83kLOYmBcEamMWICUJj1yTiipqknuDZSMfIccXdhWEXr8gpl1cVZ5G2QZVNpFl1wGJ2UvwbQx6t9M6LDD9c9pqKc2-1X7pNLb-UekxhYzJHeRko288REN8AR7czaMQtZrB2hTEJAVixUu6KPGfSHxp49K2Hy2a1UC0nlohcrJ0ERfgMJ6oZ_n_kYeLx6nHeimw
    - JWT_SECRET=BGSH12mVZbAlYny1C9KlswOORGsz0odL_NmvU-6mA_nNxXKz6nQIK6Il6L8VPYa9dZb1HwkFRDdyWqLYmjrTlQZievU9VLvmWaUlKXyIwOiXF3vqmzQy_luR-lE5v05pOqUgPhnPrQtGPvSuQpAYLFSJCX9YLJdmI0LA-0G_AvVnSjjSBnmvwZEKfHsZSRRC_cDOk8pm4A3iEMQv1_3xdwZ5GeKtkuAdNi9T31lMNlnKj-A5hZq6rfwiAWdxvCPqg44EyCKhj6c6sm2aM0qqKYb3sYMkYRmZh4GzaX8yQB3roQG-FLZ18VRm9q9YPuFavOL_L_NC8JG2Z6use4DbsQ
    - DATABASE_USER=auth
    - DATABASE_PASSWORD=auth
    - DATABASE_HOSTNAME=mysql
    - DATABASE_DB=auth
    depends_on:
    - db
    links:
    - db
# Names our volume
volumes:
  my-db:
